name: CI dev
on:
   push:
      branches: [prod]
   pull_request:
      branches: [prod]
   workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: actions/setup-node@v1
           with:
              node-version: "12.x"
         - name: Install NPM dependencies
           run: yarn install
         - name: Configure AWS Credentials dev
           uses: aws-actions/configure-aws-credentials@v1
           with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1
         - name: Deploy Next.js app master
           run: npx serverless
